// Generated by CoffeeScript 1.9.2
(function() {
  var express, path, router;

  express = require('express');

  router = express.Router();

  path = require('path');


  /* retrieve a file */

  router.get('/', function(req, res, next) {
    var mypath;
    mypath = path.join(__dirname + '\\..\\uploads\\') + req.query.img;
    res.sendFile(mypath);
  });

  module.exports = router;

}).call(this);
